### ISSUE TITLE
Update to swift 4.2

### ISSUE THREAD

**Issue by andwhy** [muyexi/StaticTableViewController#1]
Update to swift 4.2

**Comment by muyexi** [comment]
Thanks for reminding, just published 1.0.0, check it out.

**Comment by andwhy** [comment]
@muyexi thanks, but for some reason after the update StaticTableViewController folder contains only LICENSE & README files so it doesn't work of course. I use cocoapods.

**Comment by muyexi** [comment]
Updated this late in night and force-pushed an invalid podspec 🤦. Please try 1.0.1.
