### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by fritzikus1302** [muyexi/StaticTableViewController#5]
Hi its not working with iOS13 and Swift 5 please update

**Comment by mattqs** [comment]
**Package Resolution Failed.**
Xcode Version 11.4


<img width="675" alt="Screen Shot 2020-04-13 at 8 28 45 am" src="https://user-images.githubusercontent.com/7369578/79081478-28523f80-7d61-11ea-9bac-4b2aa534a734.png">

**Comment by muyexi** [comment]
@mattqs Fixed, please try again.
